name: "Chromatic - epic/7180-component-tokens"
on:
  push:
    branches: [epic/7180-component-tokens]
  pull_request:
    branches: [epic/7180-component-tokens]
    types: [labeled, synchronize]
jobs:
  run:
    if: |
      (github.event.action == 'labeled' && github.event.label.name == 'pr ready for visual snapshots') || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json
      - run: npm install
      - run: npm --workspace="packages/calcite-design-tokens" run build
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          zip: true
          exitOnceUploaded: true
          workingDir: packages/calcite-components
          # Re-enable this option once the snapshots are fixed on the epic branch. Until then, snapshots will need to be
          # approved/rejected in both the PR and the commit on epic/7180-component-tokens after installing
          # autoAcceptChanges: epic/7180-component-tokens
        env:
          STORYBOOK_SCREENSHOT_TEST_BUILD: true
          CHROMATIC_DIFF_THRESHOLD: ${{ secrets.CHROMATIC_DIFF_THRESHOLD }}
  skip:
    if: contains(github.event.pull_request.labels.*.name, 'skip visual snapshots')
    runs-on: ubuntu-latest
    steps:
      - name: Skip Chromatic
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: UI Tests
          description: Chromatic run skipped
          state: success
          sha: ${{github.event.pull_request.head.sha || github.sha}}
