name: "Chromatic"
on:
  push:
    branches: [master]
  workflow_dispatch:
  pull_request:
    branches: [master]
    types: [labeled, synchronize, ready_for_review]
jobs:
  run_snapshot_tests:
    if: "(github.event.action == 'ready_for_review' && contains(github.event.pull_request.labels.*.name, 'pr ready for visual snapshots')) || (github.event.action == 'labeled' && github.event.label.name == 'pr ready for visual snapshots' && github.event.pull_request.draft == false) || (github.event_name == 'push' && github.actor != 'dependabot[bot]' && github.actor != 'github-actions[bot]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: skip for markdown only prs
        id: one
        run: |
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          echo "branch: $current_branch"
          if [ "$current_branch" == "master" ]; then
            # diff of last commit excluding md (assumes squash merge)
            code_changes=$(git diff --name-only @~..@ -- . ':(exclude)*.md*')
            echo "push run"
          else
            # diff of branch excluding md
            code_changes=$(git diff --name-only "$current_branch" $(git merge-base "$current_branch" origin/master) -- . ':(exclude)*.md*')
            echo "pr run"
          fi
          echo "changed files: $code_changes"
          # skip if there are only md changes
          if [ -z "$code_changes" ]; then
            echo "skip chromatic"
            echo "::set-output name=skip::true"
          else
            echo "run chromatic"
            echo "::set-output name=skip::false"
          fi
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - run: npm  --legacy-peer-deps
      - if: steps.one.outputs.skip == 'false'
        name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
      - if: steps.one.outputs.skip == 'true'
        name: skip chromatic for markdown PRs
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: UI Tests
          description: Chromatic run skipped (markdown PR)
          state: success
          sha: ${{github.event.pull_request.head.sha || github.sha}}
  skip_snapshot_tests:
    if: "github.event_name == 'pull_request' && (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'pr ready for visual snapshots')) || (github.actor == 'dependabot[bot]' && github.event.action != 'labeled')"
    runs-on: ubuntu-latest
    steps:
      - name: skip chromatic for dependabot PRs or no visual changes
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: UI Tests
          description: Chromatic run skipped (not ready for snapshots or dependabot PR)
          state: success
          sha: ${{github.event.pull_request.head.sha || github.sha}}
