name: Deploy Next
on:
  push:
    branches: [benelan/screener-action]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ secrets.NEXT_RELEASE_ENABLED == "test" }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRAVIS_REPO_SLUG: "Esri/calcite-components"
      - run: npm install
      - run: npm test
      - run: bash /support/deployNextFromTravisWrapper.sh
    notify:
      runs-on: ubuntu-latest
      if: ${{ secrets.NEXT_RELEASE_ENABLED }} === "true"
      steps:
        - uses: actions/checkout@master
        - uses: skitionek/notify-microsoft-teams@master
          if: always()
          with:
            webhook_url: ${{ secrets.TEAMS_WEBHOOK_URI_BUILD }}
            needs: ${{ toJson(needs) }}
            job: ${{ toJson(job) }}
            steps: ${{ toJson(steps) }}
