name: Deploy Latest
on:
  workflow_dispatch:
  push:
    branches: [main]
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-20.04
    steps:
      - uses: google-github-actions/release-please-action@v3.7.13
        id: release
        with:
          command: manifest
          token: ${{ secrets.ADMIN_TOKEN }}
          default-branch: main
          extra-files: |
            packages/calcite-components/readme.md
      - name: Checkout Repository
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ADMIN_TOKEN }}
          ref: main
      - name: Setup Node
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          registry-url: "https://registry.npmjs.org"
      - name: Build Packages and Publish to NPM
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          npm install
          npm run build

          # These git commands can be removed once we stop tracking components.d.ts
          # For more info, see: https://github.com/Esri/calcite-design-system/pull/9011
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          # the "|| true" prevents failure if there are no changes
          git add packages/calcite-components/src/components.d.ts || true
          git commit -m "build: update types" || true

          npm run publish:latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
