name: Deploy Next
on:
  push:
    branches: [benelan/screener-action]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
        env:
          NEXT_RELEASE_ENABLED: secrets.NEXT_RELEASE_ENABLED
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRAVIS_REPO_SLUG: "Esri/calcite-components"
        if: ${{ env.NEXT_RELEASE_ENABLED }} == "true"
      - run: npm install
      - run: npm test
      - run: npm run util:deploy-next-from-travis
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
          webhook_url: ${{ secrets.TEAMS_WEBHOOK_URI_BUILD }}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}
