name: Sync designer branches with main
on: 
  pull_request:
    branches: [feature/design-tokens]
    types: [closed]
jobs:
  sync-branches:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    timeout-minutes: 2    
    steps:
      - name: Create Pull Requests
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const branches = await github.rest.repos.listBranches({ owner, repo });
            const designerBranches = branches.filter((b) => {
              return b.name.includes('designer/')
            });
            const automergeLabel = 'automated-tokens-pr';

            for (const branch of designerBranches) {
              const newPR = await github.rest.pulls.create({
                title: 'chore(automerge): Design Token Updates',
                owner,
                repo,
                head: '${{ github.ref_name }}',
                base: 'feature/design-tokens',
                body: [
                  'auto-generated: FigmaTokens PR',
                  '',
                ].join('\n')
              });

              const updatedIssueInformation = await github.rest.issues({
                owner,
                repo,
                issue_number: newPR.issue_number
              });

              const labels = updatedIssueInformation.data.labels.map(label => label.name);
              if(!labels.includes(automergeLabel)) {
                labels.push(automergeLabel)
              }

              await github.rest.issues.update({
                owner,
                repo,
                issue_number: newPR.issue_number,
                labels,
              });
            }