name: automerge
on:
  workflow_run:
      workflows: [Sync Designer Branches]
      types:
        - completed
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "automated-tokens-pr"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "chore(automatic): auto-merge from ${{github.base_ref}}"
          MERGE_REQUIRED_APPROVALS: "0"
