name: Icon Team Diff Check
on:
  pull_request:
    branches: [dev]
  pull_request_review:
    types: [submitted]
jobs:
  check-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Check changed files
        id: check-diff
        run: |
          non_icon_changes="$(
            git diff --name-only HEAD "$(
              git merge-base HEAD origin/dev
            )" -- . ':!**/calcite-ui-icons/**'
          )"

          printf "changed non-icon files:\n%s" "$non_icon_changes"

          # skip if there are changes outside of package/calcite-ui-icons
          if [ -z "$non_icon_changes" ]; then
            echo "SKIP=true" >> "$GITHUB_OUTPUT"
          else
            echo "SKIP=false" >> "$GITHUB_OUTPUT"
          fi
      - if: steps.check-diff.outputs.SKIP == 'false'
        name: Label icon PRs
        env:
          GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          gh pr edit "$PR_NUMBER" --add-label "calcite-ui-icons"
      - if: steps.check-diff.outputs.SKIP == 'false'
        name: Check pull request author and reviewers
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ADMIN_TOKEN }}
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/iconTeamDiffCheck.js')
            await action({github, context, core})
