# If the "new component" label is added to an issue, generates a notification to the CC team lead(s)
# The secret is formatted like so: lead1, lead2, lead3
# Note the script automatically adds the "@" character in to notify the leads
name: "Notify CC Leads of New Component Issue"

on:
  issues:
    types: [labeled]

jobs:
  notify-lead-new-component:
    if: github.event.label.name == 'new component'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        env:
          leads: ${{secrets.cc_leads}}
        with:
          script: |
            const { leads } = process.env;
            // Add a "@" character to notify the user
            const cc_leads = leads.split(",").map(v => " @" + v.trim());

            // Add a comment to issues with the 'new component' label to notify the lead(s)
            await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `cc ${cc_leads}`,
            });
