name: Screener
on:
  pull_request:
    branches: [master]
  # need to run on the base branch when merging to keep the baseline state up to date
  push:
    branches: [master]
jobs:
  screenshot_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: skip for markdown only prs
        id: one
        run: |
          git fetch --deepen=100
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          screenable_changes=$(git diff --name-only "$current_branch" $(git merge-base "$current_branch" origin/master) -- . ':(exclude)*.yml')
          if [ -z "$screenable_changes" ]; then
            echo "skip screener"
            echo "::set-output name=skip::skip"
          else
            echo "run screener"
            echo "::set-output name=skip::screen"
          fi
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - if: steps.one.outputs.skip == 'screen'
        name: run screener check
        env:
          SCREENER_API_KEY: ${{ secrets.SCREENER_API_KEY }}
          COMMIT_SHA: ${{github.event.pull_request.head.sha || github.sha}}
        run: |
          npm install
          npm run test:storybook || true
      - if: steps.one.outputs.skip == 'skip'
        name: skip screener
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: screener
          description: Screener run skipped (markdown PRs)
          state: success
          sha: ${{github.event.pull_request.head.sha || github.sha}}
