name: Screener
on:
  workflow_dispatch:
jobs:
  screenshot_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci --legacy-peer-deps
      - name: run screener check
        env:
          SCREENER_API_KEY: ${{ secrets.SCREENER_API_KEY }}
          COMMIT_SHA: ${{github.event.pull_request.head.sha || github.sha}}
          SAUCE_ACCESS_NAME: ${{ secrets.SAUCE_ACCESS_NAME}}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: npm run test:storybook || true
