name: Screener
on:
  pull_request_target:
    branches: [benelan/screener-action]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm install
      - run: | # gh env vars dont work in node
          npm install dotenv
          touch .env
          echo "require('dotenv').config()" | cat - screener.config.js > temp && mv temp screener.config.js
          echo SCREENER_API_KEY=${{ secrets.SCREENER_API_KEY }} >> .env
      - run: npm run test:storybook 2>&1 | tee log.txt
        if: always()
      - run: |
          URL=%(grep -Eo 'https://screener.io/v2/dashboard[^ >]+' log.txt|head -1)
          echo "::notice::View report on Screener: $URL"
