name: Screener
on:
  pull_request_target:
    branches: [benelan/screener-action]
jobs:
  screener:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: install dependencies
        run: npm install
      - name: setup environment variables
        run: | # gh env vars dont work in node
          npm install dotenv
          touch .env
          echo "require('dotenv').config()" | cat - screener.config.js > temp && mv temp screener.config.js
          echo SCREENER_API_KEY=${{ secrets.SCREENER_API_KEY }} >> .env
      - name: run screener check
        run: npm run test:storybook 2>&1 | tee log.txt
      - name: report
        if: always()
        run: |
          URL=$(grep -Eo 'https://screener.io/v2/dashboard[^ >]+' log.txt|head -1)
          echo "::set-output name=report::$URL"
      - name: create output
        uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Screener Report
          conclusion: ${{ job.status }}
          details_url: ${{ steps.report.outputs.report }}
          output: |
            {"summary": "View report on Screener: ${{ steps.report.outputs.report }}"}
