name: Sync from Airtable

on:
  # publish blog using webhook
  repository_dispatch:
    types: [airtable-update]

jobs:
  test1:
    name: Test1 (conditional run)
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github.event.client_payload) }}'
#       - run: 'echo "field: ${{ github.event.client_payload.payload[issue Number] }}"'
#       - run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
#       - run: echo baz
#         if: github.event.client_payload.payload.version == 'production'
