name: Sync to Airtable

on:
  issues:
    types: [opened, edited, closed, reopened, assigned, unassigned, labeled, unlabeled, milestoned, demilestoned]

jobs:
  send_data:
    runs-on: ubuntu-latest
    steps:
      - name: Set Data
        id: set-data
        uses: actions/github-script@v6
        env:
          SECRET: ${{ secrets.AIRTABLE_KEY }}
          WEBHOOK: ${{ secrets.AIRTABLE_WEBHOOK }}
        with:
          script: |
            const { issue, action, changes, sender } = github.event;
            return issue;
          result-encoding: string
      - name: Log Result
        run: |
          echo "${{ steps.set-data.outputs.result }}"
