name: Sync from Airtable

on:
  # publish blog using webhook
  repository_dispatch:
    types: [airtable-update]

env:
  ACTION: github.event.client_payload.action
  DATA: toJSON(github.event.client_payload.data)
  NUMBER: github.event.client_payload.number
  TITLE: github.event.client_payload.title
  OWNER: 'Esri'
  REPO: 'calcite-design-tokens'

jobs:
  existing_issue:
    name: Find Existing Issue
    runs-on: ubuntu-latest
    steps:
     - uses: actions/github-script@v6
       id: my-script
       with:
         result-encoding: string
         retries: 3
         script: |
           return github.rest.issues.get({
             issue_number: 44,
             owner: 'Esri',
             repo: 'calcite-design-tokens',
           })
