name: Sync to Airtable

on:
  issues:
    types: [opened, edited, closed, reopened, assigned, unassigned, labeled, unlabeled, milestoned, demilestoned]

# Every time an issue is edited in any way, it triggers this action.
# However, if this action is already running, we only want the latest run to complete.
# The [concurrency:group] prevents duplicate runs of the Action on the same github issue,
# while allowing concurrent runs triggered from different issues.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  allow_for_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep to allow time for multiple updates
        run: sleep .5s
        shell: bash
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Set Data
        id: set-data
        uses: actions/github-script@v6
        env:
          SECRET: ${{ secrets.AIRTABLE_KEY }}
          ISSUE: ${{ toJSON(github.event.issue) }}
          WEBHOOK: ${{ secrets.AIRTABLE_WEBHOOK }}
        with:
          script: |
            const { title, body, assignees, closed_at, created_at, id, labels, milestone, number, state, updated_at } = process.env.ISSUE;
            return body;
      - name: Log Result
        run: |
            echo "${{steps.set-data.outputs.result}}"
