name: Sync to Airtable

on:
  issues:
    types: [opened, edited, closed, reopened, assigned, unassigned, labeled, unlabeled, milestoned, demilestoned]

jobs:
  send_data:
    runs-on: ubuntu-latest
    steps:
      - name: Set Data
        id: set-data
        uses: actions/github-script@v6
        env:
          SECRET: ${{ secrets.AIRTABLE_KEY }}
          ISSUE: ${{ toJSON(github.event.issue) }}
          WEBHOOK: ${{ secrets.AIRTABLE_WEBHOOK }}
          ACTION: ${{ toJSON(github.event.action) }}
          CHANGES: ${{ toJSON(github.event.changes) }}
          SENDER: ${{ toJSON(github.event.sender) }}
        with:
          script: |
            return {
              issue: process.env.ISSUE,
              action: process.env.ACTION,
              changes: process.env.CHANGES,
              sender: process.env.SENDER
            };
      - name: Log Result
        run: |
          echo "${{ toJSON(steps.set-data.outputs) }}"
#          echo "${{steps.set-data.outputs.result}}" | echo ""
