name: Sync to Airtable

on:
  issues:
    types: [opened, edited, closed, reopened, assigned, unassigned, labeled, unlabeled, milestoned, demilestoned]

jobs:
  send_data:
    runs-on: ubuntu-latest
    steps:
      - name: Set Data
        id: set-data
        uses: actions/github-script@v6
        env:
          SECRET: ${{ secrets.AIRTABLE_KEY }}
          WEBHOOK: ${{ secrets.AIRTABLE_WEBHOOK }}
          ACTION: ${{ toJSON(github.event.action) }}
          CHANGES: ${{ toJSON(github.event.changes) }}
          ISSUE: ${{ toJSON(github.event.issue) }}
          SENDER: ${{ toJSON(github.event.sender) }}
        with:
          script: |
            const { ACTION, CHANGES, ISSUE, SENDER } = process.env;
            return SENDER;
          result-encoding: string
      - name: Log Result
        run: |
          echo "${{ toJSON(steps.set-data.outputs.result) }}"
