name: Sync from Airtable

on:
  # publish blog using webhook
  repository_dispatch:
    types: [update_issue]

jobs:
  test1:
    name: Test1 (conditional run)
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "field: ${{ github.event.client_payload.payload[issue Number] }}"'
      - run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
#       - run: echo baz
#         if: github.event.client_payload.payload.version == 'production'
