name: Release Notification
on:
  release:
    types: [published]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Get release version
        uses: actions/github-script@v4
        with:
          script: |
            const release = context.payload.release
            if (!release) {
              console.log("No release found")
              return
            }

            const data = {
              "@context": "http://schema.org/extensions",
              "@type": "MessageCard",
              title: release.tag_name,
              text: `🚀 <code>@esri/calcite-components${process.env.RELEASE_VERSION}</code> released! Check out the [changelog](https://github.com/Esri/calcite-components/blob/master/CHANGELOG.md#changelog) for more info. 🚀`
            };

            await fetch(github.secrets.TEAMS_WEBHOOK_URI_RELEASE, {
              method: "POST",
              headers: {
                "Content-Type": "application/json"
              },
              body: JSON.stringify(data)
            });
