name: automate_webhook

on:
  # Trigger the workflow when issues are updated
  issues:
    types: [opened, edited, closed, reopened, assigned, unassigned, labeled, unlabeled, milestoned, demilestoned]

# Automatically cancel any prior runs of this automation
concurrency:
      group: ${{ github.workflow }}-${{ github.event.issue.number }}-${{ github.ref }}
      cancel-in-progress: true

jobs:
  allow_for_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for .5 seconds
        run: sleep .5s
        shell: bash
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Set Data
        id: set-data
        uses: actions/github-script@v6
        env:
          SECRET: ${{ secrets.AIRTABLE_KEY }}
          ISSUE: ${{ toJSON(github.event.issue) }}
        with:
          script: |
            const { title, body, assignees, closed_at, created_at, id, labels, milestone, number, state, updated_at } = JSON.parse(process.env.ISSUE);
            const newData = { action: context.action, title, body, assignees, closed_at, created_at, id, labels, milestone, number, state, updated_at, secret: process.env.SECRET };
            console.log(newData);
#            return newData
#       - name: Webhook
#         run: |
#           curl \
#             -H "Content-Type: application/json" \
#             --data ${{steps.set-data.outputs.result}} ${{ secrets.AIRTABLE_WEBHOOK }}
#            --data '${{ env.ISSUE }}' \
#            --data '${{ secrets.AIRTABLE_KEY }}' 
#       - name: Webhook
#         uses: distributhor/workflow-webhook@v2
#         env:
#           webhook_url: ${{ secrets.AIRTABLE_WEBHOOK }}
#           webhook_secret: ${{ secrets.AIRTABLE_KEY }}
#           data: "${{env.ISSUE}}"

# jobs:
# allow time for multiple changes on an issue
  
#   get_data:
#     env:
#         ISSUE: '${{github.event.issue.assignees}}'
#     runs-on: ubuntu-latest
#     steps:
#       - name: Dump context
#         id: github_context_step
# #         run: echo '${{github.event.issue}}'
#         run: echo 'Hello'
     
    
