name: automate_webhook

on:
  # Trigger the workflow when issues are updated
  issues:
    types: [opened, edited, closed, reopened, assigned, unassigned, labeled, unlabeled, milestoned, demilestoned]

# Automatically cancel any prior runs of this automation
concurrency:
      group: ${{ github.workflow }}-${{ github.event.issue.number }}-${{ github.ref }}
      cancel-in-progress: true

jobs:
  allow_for_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 3 seconds
        run: sleep 3s
        shell: bash
  get_data:
    runs-on: ubuntu-latest
    env:
      ISSUE: '${{toJSON(github.event.issue)}}'
    steps:
      - name: Webhook
        run: |
          curl \
            -H "Content-Type: application/json" \
            --data '${{ env.ISSUE }}' \
            --data '${{ secrets.AIRTABLE_KEY }}' ${{ secrets.AIRTABLE_WEBHOOK }}
#       - name: Webhook
#         uses: distributhor/workflow-webhook@v2
#         env:
#           webhook_url: ${{ secrets.AIRTABLE_WEBHOOK }}
#           webhook_secret: ${{ secrets.AIRTABLE_KEY }}
#           data: "${{env.ISSUE}}"

# jobs:
# allow time for multiple changes on an issue
  
#   get_data:
#     env:
#         ISSUE: '${{github.event.issue.assignees}}'
#     runs-on: ubuntu-latest
#     steps:
#       - name: Dump context
#         id: github_context_step
# #         run: echo '${{github.event.issue}}'
#         run: echo 'Hello'
     
    
