name: automate_webhook

on:
  # Trigger the workflow when issues are updated
  issues:
    types: [opened, edited, closed, reopened, assigned, unassigned, labeled, unlabeled, milestoned, demilestoned]

# Automatically cancel any prior runs of this automation
concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

jobs:
# allow time for multiple changes on an issue
#   allow_for_changes:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Sleep for 10 seconds
#         run: sleep 10s
#         shell: bash

  setup_data:
    runs-on: ubuntu-latest
#     needs: allow_for_changes
    outputs:
      issue: ${{ steps.set-data.outputs.issue }}
    steps:
    - id: set-data
      run: echo "::set-output name=issue::${{toJSON(github.event.issue)}}"
#   job2:
#     needs: job1
#     runs-on: ubuntu-latest
#     strategy:
#       matrix: ${{fromJson(needs.job1.outputs.matrix)}}
#     steps:
#     - run: build

  get_data:
    needs: setup_data
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        id: github_context_step
        run: echo ${{fromJson(needs.setup_data.outputs.issue)}}
#       - name: Webhook
#         uses: distributhor/workflow-webhook@v2
#         env:
#           webhook_url: ${{ secrets.AIRTABLE_WEBHOOK }}
#           webhook_secret: ${{ secrets.AIRTABLE_KEY }}
#           data: "${{github.event.issue}}"
    
